### ISSUE TITLE
[Question] Sharding?

### ISSUE THREAD

**Issue by AlexanderTheCrafter** [TheSharks/WildBeast#605]
Hey guys! I just have a quick question for you about the topic of sharding. I was wondering, how exactly can I shard WildBeast? From what I can tell, I need to run it as multiple processes, but how exactly do I do that and set it up correctly? I remember the old docs had a page on sharding, but I cant find one on the new docs to explain this. Thanks guys! Wonderful bot software you have made BTW. 😄

**Comment by AlexanderTheCrafter** [comment]
I see something here: #319 
But that was quite some time ago, so Im not sure about how to utilize it. Wasnt that before v6?

**Comment by Dougley** [comment]
v6 has support for sharding via the environment variables `WILDBEAST_SHARDS_TOTAL`, and `WILDBEAST_SHARDS_MINE`, or by running inside a Kubernetes statefulset.

Assuming you're not running kube, you should set SHARDS_TOTAL in your .env file to how many shards you plan to run, and modulate SHARDS_MINE based on the process (pm2 probably has support for this)

**Comment by AlexanderTheCrafter** [comment]
So if I want to have two shards, I would say `WILDBEAST_SHARDS_TOTAL` to `1` (because it starts at 0). And what would `WILDBEAST_SHARDS_MINE` be? Can a single process run multiple shards? Or how does that work? Do I need to make a second WildBeast process and set the first to `0` and the second to `1`? Or can I set it to `1` as well and it will run two shards?

**Comment by Dougley** [comment]
> I would set WILDBEAST_SHARDS_TOTAL to 1 (because it starts at 0).

No, TOTAL would be 2 (you're running 2 shards *in total*)

> what would WILDBEAST_SHARDS_MINE be?

The ID of the shard starting at 0, like how you thought TOTAL would work

> Can a single process run multiple shards?

No, that's why I suggested using pm2 :)

> Do I need to make a second WildBeast process and set the first to 0 and the second to 1?

This is exactly what you need to do

**Comment by AlexanderTheCrafter** [comment]
> Do I need to make a second WildBeast process and set the first to 0 and the second to 1?
> This is exactly what you need to do
So can it run off of the same source code? Just a new docker container? Also would it also need a new arangodb and lavalink container?

**Comment by Dougley** [comment]
You could use docker-compose for this;

```yml
# This assumes WILDBEAST_SHARDS_TOTAL is in the .env file
# This also assumes the containers from the original docker-compose file are already present
services:
  wildbeast-shard-0:
    image: dougley/wildbeast
    links:
      - arango
      - lavalink
    environment: 
      - WILDBEAST_SHARDS_MINE=0
    env_file:
      - .env
  wildbeast-shard-1:
    image: dougley/wildbeast
    links:
      - arango
      - lavalink
    environment: 
      - WILDBEAST_SHARDS_MINE=1
    env_file:
      - .env
```
